In [141]:
from src import ROOT_PATH, TRAIN_PATH, TARGET_PATH, PROVIDED_DATA_PATH
from pathlib import Path
import csv
import pandas as pd
import re
import hashlib

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

TARGET_COLUMNS = [
    "Mnfr",
    "Brand",
    "Platform",
    "Segment",
    "Sub-Segment",
    "TargetAgeGroup",
]

print(ROOT_PATH)

c:\Users\sebas\PycharmProjects\Git\Critical-Materials-Recovery

In [51]:
def generate_sha256(path):

    with path.open("rb") as file:
        return hashlib.file_digest(file, "sha256").hexdigest()

In [52]:
train = pd.read_csv(TRAIN_PATH)
target = pd.read_csv(TARGET_PATH)


for df in [train,target]:

    if df is train:
        dataset = "Selfcare_Training_data (1).csv"

    if df is target:
            dataset = "Selfcare_Target_data (1).csv"

    df["dataset"] = dataset
    df["source_sha256"] = generate_sha256(PROVIDED_DATA_PATH/f"{dataset}")
    df["source_row"] = df.index
    display(df.head())

print("Training shape:", train.shape)
print("Target shape:  ", target.shape)

C:\Users\sebas\AppData\Local\Temp\ipykernel_23864\1211670601.py:1: DtypeWarning: Columns (10: Sun1, 11: Sun2, 12: Sun3, 13: Sun4, 14: Sun5, 15: Notes) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv(TRAIN_PATH)
C:\Users\sebas\AppData\Local\Temp\ipykernel_23864\1211670601.py:2: DtypeWarning: Columns (11: Sun2, 12: Sun3, 13: Sun4, 14: Sun5, 15: Notes) have mixed types. Specify dtype option on import or set low_memory=False.
  target = pd.read_csv(TARGET_PATH)

,Exclude,JoiningKey,Retailer,Category,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup,Sun1,Sun2,Sun3,Sun4,Sun5,Notes,ProductCategory,ProductBrand,ProductName,ProductRating,ProductReviewsCount,XRatXRev,ReviewsCount,Sku,Upc,ProductModelNumber,ProductUrl,ProductImageUrl,MDM_InsertDateTime,MDM_Id,ProductDescription,ProductContents,dataset,source_sha256,source_row
0,NaN,00014b3db41adfe3911aefbfa88b05af,Amazon,Self Care,All others,UnItemised brand,NaN,External Analgesics,Creams/Gels & Medicated Patches,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health & Household > Health Care > Over-the-Counter Medication > Pain Reliev...,Cora,Cora Period Menstrual Cramp Relief Kit Period Balm with Soothing Warmth (1 o...,3.9,50,15.6,4,B08QDPHXJF,NaN,NaN,https://www.amazon.com/dp/B08QDPHXJF,https://m.media-amazon.com/images/I/71XzvQ+vftL._AC_SL1500_.jpg | https://m....,45117.83254,1136754,NaN,INTUITIVELY DESIGNED. Soothe cramps where you need it most. The patch adhere...,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,0
1,NaN,00015d42f7052a8d5c9d3489d1ac5a63,Amazon,Self Care,All others,UnItemised brand,NaN,Internal Analgesics,Speciality Pain,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health & Household > Health Care > OTC Medications & Treatments > Pain Relie...,WellnessPartners,UTI Slip D-Mannose Non GMO Organic Source Veggie Capsules 90 Count (500 Mg),4.5,50,9,2,B00528Z60O,NaN,NaN,https://www.amazon.com/dp/B00528Z60O,https://m.media-amazon.com/images/I/71vOnIuiyjL._AC_SL1500_.jpg | https://m....,44936,291986,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,1
2,NaN,000220380ac4fcd79388ecf4fe26488a,Amazon,Self Care,NaN,UnItemised brand,NaN,"Vitamins, Minerals & Supplements",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Health & Household > Vitamins, Minerals & Supplements > Herbal Supplements >...",Ellie's Best,Ellie's Best Lion’s Mane Mushroom Powder Extract Supplement - USDA Organic -...,3.6,5,7.2,2,B0B3NGHTWD,NaN,NaN,https://www.amazon.com/dp/B0B3NGHTWD,https://m.media-amazon.com/images/I/81m4gRGGVkL._AC_SL1500_.jpg | https://m....,45177.76383,2506345,NaN,100% USDA CERTIFIED ORGANIC Lion's Mane Mushroom Extract. DOUBLE WATER EXTRA...,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,2
3,NaN,0003d86e9f1502b501aabd81294cfbc1,Walmart,Self Care,All others,Centrum,NaN,"Vitamins, Minerals & Supplements",Multivitamins,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health and Medicine>Vitamins and Supplements>Multivitamins>50 Plus Multivita...,Centrum,"Centrum Silver Multivitamin for Adults 50 Plus, Multimineral Supplement, 150 Ct",4.7,46,319.6,68,893202,3.00054E+11,4177-59,https://www.walmart.com/ip/Centrum-Silver-Multivitamin-for-Adults-50-Plus-Mu...,https://i5.walmartimages.com/seo/Centrum-Silver-Multivitamin-for-Adults-50-P...,44936,332923,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,3
4,NaN,000515b579fa1b8bc359d6c48569ae63,Amazon,Self Care,All others,UnItemised brand,NaN,Internal Analgesics,Speciality Pain,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health & Household > Health Care > OTC Medications & Treatments > Pain Relie...,Counterpain,Counterpain Muscular Pain Relief Hot Warm Balm 120g.,4.5,9,31.5,7,B00A1246ES,NaN,NaN,https://www.amazon.com/dp/B00A1246ES,https://m.media-amazon.com/images/I/71562Xx9MwS._AC_SL1500_.jpg | https://m....,44936,294779,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,4

,Exclude,JoiningKey,Retailer,Category,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup,Sun1,Sun2,Sun3,Sun4,Sun5,Notes,ProductCategory,ProductBrand,ProductName,ProductRating,ProductReviewsCount,XRatXRev,ReviewsCount,Sku,Upc,ProductModelNumber,ProductUrl,ProductImageUrl,MDM_InsertDateTime,MDM_Id,ProductDescription,ProductContents,dataset,source_sha256,source_row
0,NaN,000309b7492984f5f63b75a7fd898738,Amazon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Health & Household > Vitamins, Minerals & Supplements > Digestive Supplement...",Swanson,Swanson Prebiotic + Probiotic Fiber - Natural Supplement Promoting Digestive...,5,1,5,1,B0BCMTGNY6,NaN,NaN,https://www.amazon.com/dp/B0BCMTGNY6,https://m.media-amazon.com/images/I/71Tyrt2VlrL._AC_SL1200_.jpg | https://m....,45117.83254,1136755,NaN,DIGESTIVE HEALTH Support: Swanson's premium Probiotic + Prebiotic supplement...,Selfcare_Target_data (1).csv,0122a49d6e1ca5f4f0fb7a2ab381418bf0e63d9c5dc3e915d64e259a973951db,0
1,NaN,0005475457eac31e1b48113d32596657,Amazon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Health & Household > Oral Care > Oral Pain Relief > Emergency Dental Care,Topicy,"Tooth Repair Kit, Temporary Teeth Replacement Kit for Temporary Restoration ...",4.7,146,47,10,B0C5M7G2LS,NaN,NaN,https://www.amazon.com/dp/B0C5M7G2LS,https://m.media-amazon.com/images/I/71p78eoD5bL._AC_SL1500_.jpg | https://m....,45145.83061,1258179,NaN,[Safe & High Quality] The dental restoration kit uses thermoformed beads mad...,Selfcare_Target_data (1).csv,0122a49d6e1ca5f4f0fb7a2ab381418bf0e63d9c5dc3e915d64e259a973951db,1
2,NaN,0007449da680ef6267cdad691f882fc9,Amazon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Health & Household > Vitamins, Minerals & Supplements > Blended Vitamin & Mi...",MICHAEL'S,Michael's Naturopathic Programs Kidney Factors - 120 Vegetarian Tablets - Nu...,4.6,42,41.4,9,B0009RC4SU,NaN,NaN,https://www.amazon.com/dp/B0009RC4SU,https://m.media-amazon.com/images/I/61PffVGNF2L._AC_SL1500_.jpg | https://m....,44936,286907,NaN,NaN,Selfcare_Target_data (1).csv,0122a49d6e1ca5f4f0fb7a2ab381418bf0e63d9c5dc3e915d64e259a973951db,2
3,NaN,000989c388fee65a67a1b438cdcab1a0,Amazon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Health & Household > Vitamins, Minerals & Supplements > Herbal Supplements >...",Micro Ingredients,"Sustainably US Grown, Organic Barley Grass Powder, 20 Ounce (1.25 Pounds), R...",4.5,136,63,14,B01MT7T5XX,NaN,NaN,https://www.amazon.com/dp/B01MT7T5XX,https://m.media-amazon.com/images/I/614RPd5mQRL._AC_SL1366_.jpg | https://m....,44936,307895,NaN,NaN,Selfcare_Target_data (1).csv,0122a49d6e1ca5f4f0fb7a2ab381418bf0e63d9c5dc3e915d64e259a973951db,3
4,NaN,0011ea8dbe27bb276b2f8aec9a1cd142,Amazon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acid...",Toplux,Toplux Keto Pills Ketosis Diet - Natural Ketosis Using Ketone & Ketogenic Di...,3.5,1100,77,22,B094VKZZ5L,NaN,NaN,https://www.amazon.com/dp/B094VKZZ5L,https://m.media-amazon.com/images/I/81RRYFdp+bL._AC_SL1500_.jpg | https://m....,44967,372476,NaN,NaN,Selfcare_Target_data (1).csv,0122a49d6e1ca5f4f0fb7a2ab381418bf0e63d9c5dc3e915d64e259a973951db,4

Training shape: (84552, 35)
Target shape:   (28082, 35)

In [53]:
train_subset = train[TARGET_COLUMNS]
target_subset = target[TARGET_COLUMNS]

print("TRAINING PREVIEW")
display(train_subset.head())

print("TARGET PREVIEW")
display(target_subset.head())

TRAINING PREVIEW

,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup
0,All others,UnItemised brand,NaN,External Analgesics,Creams/Gels & Medicated Patches,Adult
1,All others,UnItemised brand,NaN,Internal Analgesics,Speciality Pain,Adult
2,NaN,UnItemised brand,NaN,"Vitamins, Minerals & Supplements",NaN,NaN
3,All others,Centrum,NaN,"Vitamins, Minerals & Supplements",Multivitamins,Adult
4,All others,UnItemised brand,NaN,Internal Analgesics,Speciality Pain,Adult

TARGET PREVIEW

   Mnfr  Brand  Platform  Segment  Sub-Segment  TargetAgeGroup
0   NaN    NaN       NaN      NaN          NaN             NaN
1   NaN    NaN       NaN      NaN          NaN             NaN
2   NaN    NaN       NaN      NaN          NaN             NaN
3   NaN    NaN       NaN      NaN          NaN             NaN
4   NaN    NaN       NaN      NaN          NaN             NaN

In [54]:
print("TRAINING DATA TYPES")
display(train_subset[TARGET_COLUMNS].dtypes.rename("dtype").to_frame())

print("TARGET DATA TYPES")
display(target_subset[TARGET_COLUMNS].dtypes.rename("dtype").to_frame())

TRAINING DATA TYPES

               dtype
Mnfr             str
Brand            str
Platform         str
Segment          str
Sub-Segment      str
TargetAgeGroup   str

TARGET DATA TYPES

                  dtype
Mnfr            float64
Brand           float64
Platform        float64
Segment         float64
Sub-Segment     float64
TargetAgeGroup  float64

In [55]:
print("\nUnique Platform labels:")
print(train["Platform"].value_counts(dropna=False))

Unique Platform labels:
Platform
NaN                                                                                                     83447
Extra Strength                                                                                             84
Children                                                                                                   72
Pain + Fever                                                                                               51
Oral Suspension                                                                                            49
                                                                                                        ...
12 Hour Relief                                                                                              1
 orange juice or a smoothie daily; unflavored GRASS-FED: Super Collagen Peptides powder is grass-fed        1
Cold Max                                                                                                    1
SmartCheck                                                                                                  1
Effective in 15 Minutes                                                                                     1
Name: count, Length: 64, dtype: int64

In [56]:
print("Number of Unique Platform labels:",train["Platform"].nunique())
print("Number of Unique Stripped Platform labels:",train["Platform"].astype("string").str.strip().nunique())
length_series=train["Platform"].astype("string").str.split().str.len().value_counts().sort_index()
display(length_series)

Number of Unique Platform labels: 63
Number of Unique Stripped Platform labels: 63

Platform
1     384
2     485
3     178
4      47
6      10
14      1
Name: count, dtype: int64

In [57]:
platform_col=train["Platform"].astype("string")
str_list = set()
for length in length_series.index:
    print(f"\n--- Length {length} ---")
    length_list = platform_col[platform_col.str.split().str.len() == length].unique().tolist()
    print(length_list)
    str_list.update(length_list)

--- Length 1 ---
['Cream', 'Children', 'Multi-Symptom', 'Sleep', 'Allergy', 'Complete', 'Sinus', 'Ultratabs', 'Throat', 'Immune', 'Chewables', 'Arthritis', 'Nasal', 'Precise', 'Tension', 'Head', 'PM', 'Patch', 'Gel', 'SmartCheck', 'Syrup']

--- Length 2 ---
['Red Eye', 'Regular Strength', 'Liquid Gels', 'Sinus Plus', 'Maximum Strength', 'Motrin IB', 'Dissolve Packs', 'Dual Action', 'Oral Suspension', 'Migraine Caplets', 'Extra Strength', 'Oral Solution', 'Dry Eye', 'Concentrated Drops', 'Sinus Severe', 'Imodium A-D', 'Original Strength', 'Tylenol PM', 'Simply Sleep', 'Pain Relief', 'Motrin PM', 'Coated Tabs', 'Cold Max', 'Dissolve Tablets', ' grass fed', 'Head Care']

--- Length 3 ---
['Allergy Plus Congestion', '24 Hour Relief', 'Pain + Fever', 'Cold + Flu', 'Arthritis Pain Relief', 'Vits & Supps', 'Rapid Release Gels', 'Head + Cold', 'Sinus + Headache', '12 Hour Relief']

--- Length 4 ---
['Eight Hour Arthritis Pain', 'Eight Hour Muscle Aches', 'Effective in 15 Minutes']

--- Length 6 ---
['Cough + Cold + Sore Throat', 'Cold + Cough + Runny Nose']

--- Length 14 ---
[' orange juice or a smoothie daily; unflavored GRASS-FED: Super Collagen Peptides powder is grass-fed']

In [58]:
train[train["Platform"]==" grass fed"]

,Exclude,JoiningKey,Retailer,Category,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup,Sun1,Sun2,Sun3,Sun4,Sun5,Notes,ProductCategory,ProductBrand,ProductName,ProductRating,ProductReviewsCount,XRatXRev,ReviewsCount,Sku,Upc,ProductModelNumber,ProductUrl,ProductImageUrl,MDM_InsertDateTime,MDM_Id,ProductDescription,ProductContents,dataset,source_sha256,source_row
43276,HYDROLYZED COLLAGEN: Provides some of the amino acids our bodies need to ma...,which is found in our nails and hair* AMINO ACIDS AND VITAMIN C: Nourish yo...,19 amino acids nourish the skins dermal layers; and Vitamin C,an essential antioxidant,aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C ...,gluten-free,grass fed,IGEN Non-GMO tested.* No soy wheat,lactose,"starch or artificial flavors; 3 tablets daily""","Protein, Vitamin C (as calcium ascorbate), Biotin, Sodium, Hydrolyzed bovine...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,43276
70020,HYDROLYZED COLLAGEN: Provides some of the amino acids our bodies need to ma...,which is found in our nails and hair* AMINO ACIDS AND VITAMIN C: Nourish yo...,19 amino acids nourish the skins dermal layers; and Vitamin C,an essential antioxidant,aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C ...,gluten-free,grass fed,IGEN Non-GMO tested.* No soy wheat,lactose,starch or artificial flavors; 3 tablets daily NeoCell Super Collagen + Vita...,and formulated for healthy hair,beautiful skin,and nail support.* As we age,our collagen gets depleted,which can lead to many common signs of aging. NeoCell Super Collagen + Vita...,treat,cure,or prevent any disease; This product does not contain common GE genes or pr...,Serving Size 3 Tablets. Calories: 10; Protein: 3 g; Vitamin C (as calcium as...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,70020

In [59]:
text_cols = train.select_dtypes(include=["object", "string"]).columns

str_lengths = train[text_cols].apply(lambda col: col.astype("string").str.len())
str_lengths

,Exclude,JoiningKey,Retailer,Category,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup,Sun1,Sun2,Sun3,Sun4,Sun5,Notes,ProductCategory,ProductBrand,ProductName,ProductRating,ProductReviewsCount,XRatXRev,ReviewsCount,Sku,Upc,ProductModelNumber,ProductUrl,ProductImageUrl,MDM_InsertDateTime,MDM_Id,ProductDescription,ProductContents,dataset,source_sha256
0,<NA>,32,6,9,10,16,<NA>,19,31,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117,4,154,3,2,4,1,10,<NA>,<NA>,36,459,11,7,<NA>,865,30,64
1,<NA>,32,6,9,10,16,<NA>,19,15,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,117,16,75,3,2,1,1,10,<NA>,<NA>,36,261,5,6,<NA>,<NA>,30,64
2,<NA>,32,6,9,<NA>,16,<NA>,32,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,86,12,135,3,1,3,1,10,<NA>,<NA>,36,542,11,7,<NA>,1396,30,64
3,<NA>,32,7,9,10,7,<NA>,32,13,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,80,7,79,3,2,5,2,6,11,7,111,1998,5,6,<NA>,<NA>,30,64
4,<NA>,32,6,9,10,16,<NA>,19,15,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,141,11,52,3,1,4,1,10,<NA>,<NA>,36,129,5,6,<NA>,<NA>,30,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84547,7,32,7,9,10,16,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,34,9,92,3,2,4,1,9,12,<NA>,129,638,11,6,893,9,30,64
84548,7,32,6,9,10,9,<NA>,19,15,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,141,9,194,3,3,2,2,10,<NA>,<NA>,36,438,5,6,<NA>,<NA>,30,64
84549,7,32,7,9,10,12,<NA>,<NA>,<NA>,5,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,101,8,79,3,3,5,2,9,11,<NA>,116,1038,5,6,<NA>,<NA>,30,64
84550,7,32,7,9,<NA>,12,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,89,7,188,1,1,2,1,10,12,4,176,949,11,7,3105,<NA>,30,64
84551,7,32,6,9,<NA>,7,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,97,7,47,3,1,1,1,10,<NA>,<NA>,36,313,11,7,<NA>,599,30,64

In [60]:
def run_whitelist_filter(df:pd.DataFrame)-> pd.DataFrame:
    df["Q_REASON"] = [[] for _ in range(len(df))]
    return df, None

    # quarantined_df = None

    # for col in TARGET_COLUMNS:
    #     non_whitelist_df = df[df[col]!=f"{col}_whitelist"]
    #     non_whitelist_df["Q_REASON"].append(1)
    #     quarantined_df.concat(non_whitelist_df)


    # quarantined_df=quarantined_df.drop_duplicates
    # return df.drop(index=quarantined_df.index), quarantined_df

In [61]:
def get_label_occurance(df:pd.DataFrame, col:str) -> pd.Series:

    current_col=df[col].astype("string")
    label_occurance = current_col.value_counts().sort_index()

    return label_occurance

In [62]:
def iqr_bounds(series, multiplier=1.5):
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower = q1 - (multiplier * iqr)
    upper = q3 + (multiplier * iqr)

    return lower, upper

In [63]:
def get_missingingness_bounds(df:pd.DataFrame):
    return iqr_bounds(df.isna().mean(axis=1))

In [64]:
def get_label_len_bound(df:pd.DataFrame):
    text_cols = df.select_dtypes(include=["object", "string"]).columns
    str_lengths = df[text_cols].apply(lambda col: col.astype("string").str.len())
    return iqr_bounds(str_lengths.mean(axis=1))

In [95]:
def check_target_cols(df:pd.DataFrame):
    df, quarantined_df = run_whitelist_filter(df)

    quarantined_rows = []

    # checking criteria for each target column
    for col in TARGET_COLUMNS:
        print(f"\n---{col}---")
        current_col=df[col].astype("string")

        # get limits for label occurance per target column
        occurance_series = get_label_occurance(df,col)
        lower_occurance, _ = iqr_bounds(occurance_series)

        # get a list of all labels
        label_list = set(current_col.dropna().unique())

        # check each label's first index for whitespace or lower case letters
        for label in label_list:
            label_occurance = (current_col == label).sum()
            # `if label...` for empty strings ""
            if label and (label.startswith(" ") or label[0].islower()):
                print(
                    f"Label: {label} is ABNORMAL\n"
                )

                faulty_label_df = df[df[col] == label].copy()
                faulty_label_df["Q_REASON"] = faulty_label_df["Q_REASON"].apply(lambda x: x + [2])
                quarantined_rows.append(faulty_label_df)

            # check if a label occurance outside the normal occurance bounds
            if (label_occurance < lower_occurance) :
                print(
                    f"Label: {label}, \n"
                    f"Avg. lower occurance bound: {lower_occurance}, \n"
                    f"Number of rows: {label_occurance}\n"
                )

                abnormal_occurance_df = df[df[col] == label].copy()
                abnormal_occurance_df = abnormal_occurance_df["Q_REASON"].apply(lambda x: x + [3])
                quarantined_rows.append(abnormal_occurance_df)

    text_cols = df.select_dtypes(include=["object", "string"]).columns
    str_df = df[text_cols].apply(lambda col: col.astype("string").str.len())

    # bounds for missingness per row
    lower_missingness, upper_missingness = get_missingingness_bounds(str_df)

    # bounds for label length per row
    lower_row_len, upper_row_len  = get_label_len_bound(df)

    # calculate every rows' missingness
    missingness = str_df.isna().mean(axis=1)

    # calculate every rows' average text length
    row_len = str_df.mean(axis=1)

    mask = (
        ((missingness < lower_missingness) |
        (missingness > upper_missingness)) &
        ((row_len < lower_row_len) |
        (row_len > upper_row_len))
    )

    df.loc[mask, "Q_REASON"] = df.loc[mask,"Q_REASON"].apply(
        lambda x: x + [4]
    )
    print("Number of rows with ABNORMAL charateristics:",mask.sum())
    
    quarantined_rows.append(df[mask].copy())    

    """
    try to turn all columns numeric.
    faulty rows tend to replace numeric columns with str, so
    they will have NA across the entire row.
    """
    numeric = df.apply(pd.to_numeric, errors="coerce")
    non_numeric_mask = numeric.isna().all(axis=1)

    df.loc[non_numeric_mask, "Q_REASON"] = df.loc[non_numeric_mask, "Q_REASON"].apply(
    lambda x: x + [5]
    )
    
    print("Number of rows with no numeric values:",non_numeric_mask.sum())
    quarantined_rows.append(df[non_numeric_mask].copy())

    if quarantined_df is not None:
        quarantined_rows.insert(0, quarantined_df)
    
    quarantined_df = pd.concat(
    quarantined_rows,
    ignore_index=False
    )

    quarantined_df = quarantined_df[
        ~quarantined_df.index.duplicated(keep="first")
    ]

    df = df.drop(index=quarantined_df.index)

    return df, quarantined_df

filtered_train, quarantined_df=check_target_cols(train)

---Mnfr---
Label:  coffee is ABNORMAL

Label:  aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C & Biotin is Keto certified is ABNORMAL


---Brand---
Label:  gluten-free is ABNORMAL

Label:  tea is ABNORMAL

Label: up & up is ABNORMAL


---Platform---
Label:  orange juice or a smoothie daily; unflavored GRASS-FED: Super Collagen Peptides powder is grass-fed is ABNORMAL

Label:  grass fed is ABNORMAL


---Segment---
Label:  Keto certified is ABNORMAL

Label:  IGEN Non-GMO tested.* No soy wheat is ABNORMAL


---Sub-Segment---
Label:  gluten-free is ABNORMAL

Label:  lactose is ABNORMAL


---TargetAgeGroup---
Label:  starch or artificial flavors; 3 tablets daily NeoCell Super Collagen + Vitamin C and Biotin is made with grass-fed hydrolyzed collagen is ABNORMAL

Label:  starch or artificial flavors; 3 tablets daily" is ABNORMAL

Label:  Paleo friendly is ABNORMAL

Number of rows with ABNORMAL charateristics: 0
Number of rows with no numeric values: 0

In [96]:
display(quarantined_df.head())

,Exclude,JoiningKey,Retailer,Category,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup,Sun1,Sun2,Sun3,Sun4,Sun5,Notes,ProductCategory,ProductBrand,ProductName,ProductRating,ProductReviewsCount,XRatXRev,ReviewsCount,Sku,Upc,ProductModelNumber,ProductUrl,ProductImageUrl,MDM_InsertDateTime,MDM_Id,ProductDescription,ProductContents,dataset,source_sha256,source_row,Q_REASON
21527,SUPPORTS COLLAGEN FORMATION FOR MEN AND WOMEN: Collagen supplement for men ...,promotes healthy collagen formation throughout the body,and supports healthy joints* SUGGESTED USE FOR MONTHLY SUPPLY: 30-day,1-month supply; simply dissolve 2 scoops of Super Collagen Peptides powder ...,coffee,tea,orange juice or a smoothie daily; unflavored GRASS-FED: Super Collagen Pept...,Keto certified,gluten-free,Paleo friendly,IGEN Non-GMO tested;* contains no soy wheat,lactose,starch,"corn or artificial flavors""",Serving Size 2 Scoops (20 g). Servings per Container 30. Calories: 70; Prote...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,21527,[2]
43276,HYDROLYZED COLLAGEN: Provides some of the amino acids our bodies need to ma...,which is found in our nails and hair* AMINO ACIDS AND VITAMIN C: Nourish yo...,19 amino acids nourish the skins dermal layers; and Vitamin C,an essential antioxidant,aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C ...,gluten-free,grass fed,IGEN Non-GMO tested.* No soy wheat,lactose,"starch or artificial flavors; 3 tablets daily""","Protein, Vitamin C (as calcium ascorbate), Biotin, Sodium, Hydrolyzed bovine...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,43276,[2]
70020,HYDROLYZED COLLAGEN: Provides some of the amino acids our bodies need to ma...,which is found in our nails and hair* AMINO ACIDS AND VITAMIN C: Nourish yo...,19 amino acids nourish the skins dermal layers; and Vitamin C,an essential antioxidant,aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C ...,gluten-free,grass fed,IGEN Non-GMO tested.* No soy wheat,lactose,starch or artificial flavors; 3 tablets daily NeoCell Super Collagen + Vita...,and formulated for healthy hair,beautiful skin,and nail support.* As we age,our collagen gets depleted,which can lead to many common signs of aging. NeoCell Super Collagen + Vita...,treat,cure,or prevent any disease; This product does not contain common GE genes or pr...,Serving Size 3 Tablets. Calories: 10; Protein: 3 g; Vitamin C (as calcium as...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,70020,[2]
670,NaN,03e11eff79a67a9bbca98c0c74309127,Target,Self Care,All others,up & up,NaN,Internal Analgesics,Internal Pain,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health > Medicines & Treatments > Pain & Fever,up & up,Aspirin (NSAID) Regular Strength Pain Reliever & Fever Reducer Coated Tablet...,4.72,17,33.04,7,11004683,70030632687,NaN,https://www.target.com/p/-/A-11004683,https://target.scene7.com/is/image/Target/GUEST_32d7afb6-ad33-4079-9816-d461...,44936,324782,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,670,[2]
901,NaN,058dfdcb710822c49364b80db95265bc,Target,Self Care,All others,up & up,NaN,CCFS,Sore Throat / Cough Drops,Adult,NaN,NaN,NaN,NaN,NaN,NaN,"Health > Medicines & Treatments > Cough, Cold & Flu",up & up,Relief Liquid Combo Pack for Cold & Sore Throat - 12 fl oz - up & up,4.6,6,27.6,6,79709945,8.29576E+11,NaN,https://www.target.com/p/-/A-79709945,https://target.scene7.com/is/image/Target/GUEST_b41a8c3c-8cf3-46bd-b817-149f...,44936,323799,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,901,[2]

In [97]:
len(quarantined_df)

245

In [101]:
len(filtered_train)

84307

In [131]:
display(filtered_train)

,Exclude,JoiningKey,Retailer,Category,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup,Sun1,Sun2,Sun3,Sun4,Sun5,Notes,ProductCategory,ProductBrand,ProductName,ProductRating,ProductReviewsCount,XRatXRev,ReviewsCount,Sku,Upc,ProductModelNumber,ProductUrl,ProductImageUrl,MDM_InsertDateTime,MDM_Id,ProductDescription,ProductContents,dataset,source_sha256,source_row,Q_REASON
0,NaN,00014b3db41adfe3911aefbfa88b05af,Amazon,Self Care,All others,UnItemised brand,NaN,External Analgesics,Creams/Gels & Medicated Patches,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health & Household > Health Care > Over-the-Counter Medication > Pain Reliev...,Cora,Cora Period Menstrual Cramp Relief Kit Period Balm with Soothing Warmth (1 o...,3.9,50,15.6,4,B08QDPHXJF,NaN,NaN,https://www.amazon.com/dp/B08QDPHXJF,https://m.media-amazon.com/images/I/71XzvQ+vftL._AC_SL1500_.jpg | https://m....,45117.83254,1136754,NaN,INTUITIVELY DESIGNED. Soothe cramps where you need it most. The patch adhere...,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,0,[]
1,NaN,00015d42f7052a8d5c9d3489d1ac5a63,Amazon,Self Care,All others,UnItemised brand,NaN,Internal Analgesics,Speciality Pain,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health & Household > Health Care > OTC Medications & Treatments > Pain Relie...,WellnessPartners,UTI Slip D-Mannose Non GMO Organic Source Veggie Capsules 90 Count (500 Mg),4.5,50,9,2,B00528Z60O,NaN,NaN,https://www.amazon.com/dp/B00528Z60O,https://m.media-amazon.com/images/I/71vOnIuiyjL._AC_SL1500_.jpg | https://m....,44936,291986,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,1,[]
2,NaN,000220380ac4fcd79388ecf4fe26488a,Amazon,Self Care,NaN,UnItemised brand,NaN,"Vitamins, Minerals & Supplements",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Health & Household > Vitamins, Minerals & Supplements > Herbal Supplements >...",Ellie's Best,Ellie's Best Lion’s Mane Mushroom Powder Extract Supplement - USDA Organic -...,3.6,5,7.2,2,B0B3NGHTWD,NaN,NaN,https://www.amazon.com/dp/B0B3NGHTWD,https://m.media-amazon.com/images/I/81m4gRGGVkL._AC_SL1500_.jpg | https://m....,45177.76383,2506345,NaN,100% USDA CERTIFIED ORGANIC Lion's Mane Mushroom Extract. DOUBLE WATER EXTRA...,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,2,[]
3,NaN,0003d86e9f1502b501aabd81294cfbc1,Walmart,Self Care,All others,Centrum,NaN,"Vitamins, Minerals & Supplements",Multivitamins,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health and Medicine>Vitamins and Supplements>Multivitamins>50 Plus Multivita...,Centrum,"Centrum Silver Multivitamin for Adults 50 Plus, Multimineral Supplement, 150 Ct",4.7,46,319.6,68,893202,3.00054E+11,4177-59,https://www.walmart.com/ip/Centrum-Silver-Multivitamin-for-Adults-50-Plus-Mu...,https://i5.walmartimages.com/seo/Centrum-Silver-Multivitamin-for-Adults-50-P...,44936,332923,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,3,[]
4,NaN,000515b579fa1b8bc359d6c48569ae63,Amazon,Self Care,All others,UnItemised brand,NaN,Internal Analgesics,Speciality Pain,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health & Household > Health Care > OTC Medications & Treatments > Pain Relie...,Counterpain,Counterpain Muscular Pain Relief Hot Warm Balm 120g.,4.5,9,31.5,7,B00A1246ES,NaN,NaN,https://www.amazon.com/dp/B00A1246ES,https://m.media-amazon.com/images/I/71562Xx9MwS._AC_SL1500_.jpg | https://m....,44936,294779,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,4,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84547,Exclude,ffa0a5ff71c469e5de00ebcbb8b126e2,Walmart,Self Care,All others,UnItemised brand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Baby > Health & Safety > FridaBaby,FridaBaby,FridaBaby Baby Nasal Aspirator 20 Hygiene Filters for NoseFrida The Snotsuck...,4.6,16,18.4,4,365106318,851877006141,NaN,https://www.walmart.com/ip/FridaBaby-Baby-Nasal-Aspirator-20-Hygiene-Filters...,https://i5.walmartimages.com/seo/FridaBaby-Baby-Nasal-Aspirator-20-Hygiene-F...,45055.70023,590171,Disposable filters are clinically proven to prevent the transfer of mucus or...,essential,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,84547,[]
84548,Exclude,ffc4318028d47131abcb1dbccf8644b2,Amazon,Self Care,All others,Biofreeze,NaN,Internal Analgesics,Speciality Pain,Adult,NaN,NaN,NaN,NaN,NaN,NaN,Health & Household > Health Care > OTC Medications & Treatments > Pain Relie...,Biofreeze,Biofreeze Overnight Pain Relief Patches (4 Per Box) And Large Pain Relief Pa...,4.5,794,54,12,B0BBSX3ML1,NaN,NaN,https://www.amazon.com/dp/B0BBSX3ML1,https://m.media-amazon.com/images/I/81m0UH3lXiL._SL1500_.jpg | https://m.med...,44967,384846,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,84548,[]
84549,Exclude,ffce1b597e81c30fa506d07d2d77a793,Walmart,Self Care,All others,Other Brands,NaN,NaN,NaN,Adult,NaN,NaN,NaN,NaN,NaN,NaN,"Sports & Outdoors>Exercise & Fitness>Sports Recovery, Injury Prevention>Spor...",DZT 1968,3D Weaving Knee Brace Breathable Sleeve Support for Running Jogging Sports 1pcs,3.4,119,241.4,71,597825098,6.50876E+11,NaN,https://www.walmart.com/ip/3D-Weaving-Knee-Brace-Breathable-Sleeve-Support-f...,https://i5.walmartimages.com/seo/3D-Weaving-Knee-Brace-Breathable-Sleeve-Sup...,44936,329926,NaN,NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,84549,[]
84550,Exclude,ffe828d713915aec91b29d35cc3aba2e,Walmart,Self Care,NaN,Other Brands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Health and Medicine > Home Health Care > Braces and Supports > Knee Support ...,Cambivo,"CAMBIVO Knee Brace with Side Stabilizers, Knee Sleeve for Knee Pain, Adjusta...",5,8,30,6,1948756989,799177839703,NS90,https://www.walmart.com/ip/CAMBIVO-Knee-Brace-Side-Stabilizers-Sleeve-Pain-A...,https://i5.walmartimages.com/asr/017a7900-a346-490d-a06a-9a216ff86ee5.69b62a...,45117.83254,1147490,"CAMBIVO is an exclusive patented brand in the United States,designed in Cali...",NaN,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,84550,[]
84551,Exclude,fff34a4c2897fe6d8d4d33ed35fa7617,Amazon,Self Care,NaN,Generic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Health & Household > Health Care > Over-the-Counter Medication > Pain Reliev...,Generic,hemorrhoial Relief with Aloe Vera Suppositories,3.5,2,7,2,B0BX789WPV,NaN,NaN,https://www.amazon.com/dp/B0BX789WPV,https://m.media-amazon.com/images/I/51ixVpW+ziL._AC_SL1400_.jpg | https://m....,45145.83061,1266252,NaN,STOP OF THE SUFFER : hemorrhoid suppository was made from natural ingredient...,Selfcare_Training_data (1).csv,00f1fcd0d45bc4196ea8c0e9fffa63897c8e24d12a7639468928fbd6afff4452,84551,[]

In [137]:
shared_subsegments = (
    filtered_train.dropna(subset=["Segment", "Sub-Segment"])
    .groupby("Sub-Segment")["Segment"]
    .nunique()
)

shared_names = shared_subsegments[shared_subsegments > 1].index

display(
    filtered_train.loc[
        filtered_train["Sub-Segment"].isin(shared_names),
        ["Segment", "Sub-Segment"]
    ]
    .drop_duplicates()
    .sort_values(["Sub-Segment", "Segment"])
)

                                Segment    Sub-Segment
76724               External Analgesics  Internal Pain
73                  Internal Analgesics  Internal Pain
2328                   Digestive Health     Probiotics
109    Vitamins, Minerals & Supplements     Probiotics

The statement ‘a child class cannot have more rows than its parent’ only holds when the child has a single parent; shared Sub-Segments can have a total row count larger than any one parent because their rows are distributed across multiple Segments.

In [138]:
# How many rows each Segment has
parent_counts = filtered_train["Segment"].value_counts()

# How many total rows each Sub-Segment has
child_counts = filtered_train["Sub-Segment"].value_counts()

# Unique Segment/Sub-Segment relationships
relationships = (
    filtered_train.dropna(subset=["Segment", "Sub-Segment"])
    [["Segment", "Sub-Segment"]]
    .drop_duplicates()
)

# Number of parents each Sub-Segment belongs to
num_parents = (
    relationships
    .groupby("Sub-Segment")["Segment"]
    .nunique()
)

# Add counts
relationships["num_parents"] = relationships["Sub-Segment"].map(num_parents)
relationships["subsegment_rows"] = relationships["Sub-Segment"].map(child_counts)
relationships["parent_rows"] = relationships["Segment"].map(parent_counts)

# Does the child's TOTAL count exceed this parent's total count?
relationships["child_gt_parent"] = (
    relationships["subsegment_rows"] > relationships["parent_rows"]
)

display(
    relationships.sort_values(
        ["num_parents", "Sub-Segment"]
    )
)

,Segment,Sub-Segment,num_parents,subsegment_rows,parent_rows,child_gt_parent
15,Digestive Health,Acid Relief,1,1137,7052,False
70,Digestive Health,All Other Digestive Health,1,2126,7052,False
337,Allergy,Allergy INS,1,579,2709,False
246,Digestive Health,Anti-Diarrheal,1,230,7052,False
111,Digestive Health,Anti-Gas,1,370,7052,False
5214,Digestive Health,Anti-Nausea,1,57,7052,False
9,External Analgesics,Cold & Heat Wraps,1,3818,6064,False
21581,CCFS,Cold / Flu,1,4,4234,False
159,CCFS,Cold/Flu,1,1281,4234,False
241,Digestive Health,Constipation Remedies,1,1727,7052,False
222,CCFS,Cough,1,591,4234,False
16167,External Analgesics,Creams & Gels (Rubs),1,1,6064,False
0,External Analgesics,Creams/Gels & Medicated Patches,1,1008,6064,False
68923,Lifestyle CHC,Daily oral contracception,1,2,4538,False
50579,Other Self Care,Dermatologicals,1,4,1125,False
6229,External Analgesics,Devices/Refills,1,14,6064,False
49,Digestive Health,Digestive enzymes,1,393,7052,False
22,Lifestyle CHC,Ear Care,1,3089,4538,False
69,CCFS,External Upper Respiratory,1,154,4234,False
74,Other Self Care,Eye Care,1,1020,1125,False
5219,Digestive Health,Hemorrhoid Remedies,1,209,7052,False
5,"Vitamins, Minerals & Supplements",Herbal & Natural (H&N),1,10559,49036,False
552,Digestive Health,Lactose Intolerance,1,42,7052,False
705,"Vitamins, Minerals & Supplements",Menopausal Support,1,113,49036,False
10,"Vitamins, Minerals & Supplements",Minerals,1,7551,49036,False
5195,Digestive Health,Motion Sickness,1,407,7052,False
3,"Vitamins, Minerals & Supplements",Multivitamins,1,3414,49036,False
500,CCFS,Nasal Sprays,1,457,4234,False
134,Lifestyle CHC,Obesity treatments,1,393,4538,False
24,Allergy,Oral Antihistamine,1,820,2709,False
83,Allergy,Other Allergy,1,859,2709,False
14,External Analgesics,Other External Analgesics,1,779,6064,False
11036,Lifestyle CHC,Other Lifestyle,1,3,4538,False
44,Lifestyle CHC,Other Lifestyle CHC,1,195,4538,False
2270,Other Self Care,Other Self Care,1,101,1125,False
95,"Vitamins, Minerals & Supplements",Pregnancy Vitamins,1,356,49036,False
34,Lifestyle CHC,Prostate Remedies,1,233,4538,False
17274,Internal Analgesics,Remaining Internal Pain,1,11,4761,False
23,"Vitamins, Minerals & Supplements",Single Vitamins,1,4923,49036,False
42,CCFS,Sinus excl Sprays,1,430,4234,False
55,Internal Analgesics,Sleep Aids,1,1057,4761,False
65,CCFS,Sore Throat / Cough Drops,1,1317,4234,False
1,Internal Analgesics,Speciality Pain,1,1753,4761,False
63,Lifestyle CHC,Stimulants,1,10,4538,False
7,"Vitamins, Minerals & Supplements",Supplements,1,19525,49036,False
77,Lifestyle CHC,Systemic Cardiovasculars,1,521,4538,False
379,External Analgesics,Temperature Packs,1,436,6064,False
2289,Allergy,Topical Itch,1,32,2709,False
528,Lifestyle CHC,Urinary products,1,92,4538,False
73,Internal Analgesics,Internal Pain,2,1940,4761,False
76724,External Analgesics,Internal Pain,2,1940,6064,False
109,"Vitamins, Minerals & Supplements",Probiotics,2,650,49036,False
2328,Digestive Health,Probiotics,2,650,7052,False

In [139]:
def check_single_parent_counts(
    df,
    parent_col="Segment",
    child_col="Sub-Segment"
):
    # only use complete parent-child pairs to determine relationships
    relationships = df.dropna(
        subset=[parent_col, child_col]
    )

    # number of observed parents for each child
    parent_counts_per_child = (
        relationships
        .groupby(child_col)[parent_col]
        .nunique()
    )

    # children with exactly one observed parent
    single_parent_children = (
        parent_counts_per_child[
            parent_counts_per_child == 1
        ].index
    )

    # find that single parent
    child_to_parent = (
        relationships[
            relationships[child_col].isin(single_parent_children)
        ]
        .groupby(child_col)[parent_col]
        .first()
    )

    # total counts across dataset
    child_counts = df[child_col].value_counts()
    parent_counts = df[parent_col].value_counts()

    results = []

    for child, parent in child_to_parent.items():

        child_rows = child_counts.get(child, 0)
        parent_rows = parent_counts.get(parent, 0)

        if child_rows > parent_rows:
            results.append({
                child_col: child,
                parent_col: parent,
                "child_rows": child_rows,
                "parent_rows": parent_rows,
                "difference": child_rows - parent_rows
            })

    return pd.DataFrame(results)

In [140]:
violations = check_single_parent_counts(train)

display(violations)

Empty DataFrame
Columns: []
Index: []

In [143]:
def find_format_duplicates(df, col):
    labels = df[col].dropna().astype("string")

    def normalize_label(label):
        label = label.strip()
        label = re.sub(r"\s*/\s*", "/", label)
        label = re.sub(r"\s+", " ", label)
        return label.casefold()

    temp = pd.DataFrame({
        "original": labels,
        "normalized": labels.map(normalize_label)
    })

    groups = (
        temp.groupby("normalized")["original"]
        .agg(lambda x: sorted(set(x)))
    )

    # Only return normalized labels that came from
    # more than one original spelling
    return groups[groups.apply(len) > 1]

In [145]:
for col in TARGET_COLUMNS:
    print(find_format_duplicates(filtered_train, col))

Series([], Name: original, dtype: object)
Series([], Name: original, dtype: object)
Series([], Name: original, dtype: object)
Series([], Name: original, dtype: object)
normalized
cold/flu    [Cold / Flu, Cold/Flu]
Name: original, dtype: object
Series([], Name: original, dtype: object)

In [146]:
filtered_train.loc[
    train["Sub-Segment"].isin([
        "Other Lifestyle CHC",
        "Other Lifestyle"
    ]),
    ["Segment", "Sub-Segment"]
].value_counts()

Segment        Sub-Segment
Lifestyle CHC  Other Lifestyle CHC    195
               Other Lifestyle          3
Name: count, dtype: int64

In [147]:
target.loc[
    train["Sub-Segment"].isin([
        "Other Lifestyle CHC",
        "Other Lifestyle"
    ]),
    ["Segment", "Sub-Segment"]
].value_counts()

Series([], Name: count, dtype: int64)

In [148]:
small = train[train["Sub-Segment"] == "Other Lifestyle"]
large = train[train["Sub-Segment"] == "Other Lifestyle CHC"]

small_products = set(small["ProductName"].dropna())
large_products = set(large["ProductName"].dropna())

overlap = small_products & large_products

print("Matching products:", len(overlap))
display(overlap)

Matching products: 0

set()

In [149]:
for col in ["Upc", "Sku", "ProductUrl"]:
    small_values = set(small[col].dropna())
    large_values = set(large[col].dropna())

    overlap = small_values & large_values

    print(f"{col}: {len(overlap)} matches")
    print(overlap)

Upc: 0 matches
set()
Sku: 0 matches
set()
ProductUrl: 0 matches
set()

In [150]:
display(
    train.loc[
        train["Sub-Segment"] == "Other Lifestyle",
        [
            "Segment",
            "Sub-Segment",
            "ProductCategory",
            "ProductName",
            "Brand"
        ]
    ]
)

,Segment,Sub-Segment,ProductCategory,ProductName,Brand
11036,Lifestyle CHC,Other Lifestyle,"Health & Household > Health Care > OTC Medications & Treatments > Allergy, S...",ORGANIC VITALITY Premium Berberine HCL Supplement - 1200mg of Berberine Per ...,Other Brands
37964,Lifestyle CHC,Other Lifestyle,Beauty>Skin Care>Lip Care>Lip Balm & Conditioner,Abreva Docosanol 10% Fever Blister and Cold Sore Treatment .07 oz 2 Pk,Other Brands
59491,Lifestyle CHC,Other Lifestyle,Beauty>Skin Care>Lip Care>Lip Balm & Conditioner,"Abreva Docosanol 10% Fever Blister and Cold Sore Treatment, 0.07 Oz",Other Brands

In [151]:
display(
    train.loc[
        train["Sub-Segment"] == "Other Lifestyle CHC",
        [
            "Segment",
            "Sub-Segment",
            "ProductCategory",
            "ProductName",
            "Brand"
        ]
    ].head(20)
)

,Segment,Sub-Segment,ProductCategory,ProductName,Brand
44,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Health Care > Eye Health > Dry Eye Relief,NaN,UnItemised brand
243,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Health Care > Eye Health,"Dr. Fischer Premium, Purified, Non-Irritating & Hypoallergenic Eyelid Wipes ...",UnItemised brand
442,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Health Care > Eye Health,"Quality Choice Eyelid Cleansing Wipes, Sensitive Mild Formula, 30ct",UnItemised brand
860,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Oral Care > Oral Pain Relief,CAILING 4 PCS Professional Snap On Teeth Fake Braces for Teeth for Cosmetic ...,UnItemised brand
1237,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Health Care > OTC Medications & Treatments > Pain Relie...,"Plush Uterus Menstrual Heating Pad for Cramps, Funny Plushie Gift for First ...",UnItemised brand
1398,Lifestyle CHC,Other Lifestyle CHC,Health > Eye Care,Saline Solution for Sensitive Eyes - 24 fl oz - up & up,up & up
2276,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Oral Care > Oral Pain Relief,Baltic Amber Necklace and Amber Bracelet - Natural Amber from Baltic Region ...,UnItemised brand
2290,Lifestyle CHC,Other Lifestyle CHC,Health and Medicine>Equate>Equate Eye Care>Equate Eye Care Products,Equate Contact Lens Case- 6CT,Equate
2468,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Health Care > Eye Health > Dry Eye Relief,"Ocusoft Retaine MGD Ophthalmic Emulsion, Milky White Solution, 30 count Sing...",UnItemised brand
2547,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Health Care > Eye Health,Hycosan Night,UnItemised brand
2755,Lifestyle CHC,Other Lifestyle CHC,Health > Eye Care,ICU Eyewear Screen Vision Blue Light Filtering Rectangular Glasses - Dark To...,UnItemised brand
3802,Lifestyle CHC,Other Lifestyle CHC,Shop>Personal Care>Eye Care>Reading Glasses,Pearla Reading Glasses Teal,UnItemised brand
4475,Lifestyle CHC,Other Lifestyle CHC,Health > Eye Care,Zeiss Anti Fog Wipes - 30ct,UnItemised brand
4541,Lifestyle CHC,Other Lifestyle CHC,Health > Eye Care,TheraTears Sterilid Antimicrobial Eyelid Cleanser and Facial Wash - 2 fl oz,UnItemised brand
4582,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Health Care > Eye Health > Dry Eye Relief,"Blink Tears Sterile Single Use Vials, 25 Count, 0.01 Fluid Ounce Each",UnItemised brand
4667,Lifestyle CHC,Other Lifestyle CHC,Health and Medicine>Eye Care>Hard Contact Solution,"Opti-Free Puremoist Multi-purpose Contact Lens Solution, Twin Pack",UnItemised brand
4888,Lifestyle CHC,Other Lifestyle CHC,Health > Eye Care,ICU Eyewear Titanium Reading Glasses - +1.25,UnItemised brand
5735,Lifestyle CHC,Other Lifestyle CHC,Health > Eye Care,Lens Cleaner Spray - 4 fl oz - up & up,up & up
5938,Lifestyle CHC,Other Lifestyle CHC,Health & Household > Oral Care > Oral Pain Relief,"Denture Teeth Temporary Fake TeethSnap On Veneers, Snap in Teeth for Men and...",UnItemised brand
5984,Lifestyle CHC,Other Lifestyle CHC,Beauty > Bath & Body > Spa & Massage > Light & Sound Therapy,"Yogasleep Dohm Classic White Noise Sound Machine, Tan",UnItemised brand

In [153]:
train.loc[
    train["Sub-Segment"] == "Other Lifestyle",
    "Sub-Segment"
] = "Other Lifestyle CHC"