In [3]:
from src import ROOT_PATH, TRAIN_PATH, TARGET_PATH
from pathlib import Path
import csv
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

TARGET_COLUMNS = [
    "Mnfr",
    "Brand",
    "Platform",
    "Segment",
    "Sub-Segment",
    "TargetAgeGroup",
]

print(ROOT_PATH)

c:\Users\sebas\PycharmProjects\Git\Critical-Materials-Recovery

In [4]:
train = pd.read_csv(TRAIN_PATH)
target = pd.read_csv(TARGET_PATH)

print("Training shape:", train.shape)
print("Target shape:  ", target.shape)

C:\Users\sebas\AppData\Local\Temp\ipykernel_3968\969169418.py:1: DtypeWarning: Columns (10: Sun1, 11: Sun2, 12: Sun3, 13: Sun4, 14: Sun5, 15: Notes) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv(TRAIN_PATH)

Training shape: (84552, 32)
Target shape:   (28082, 32)

C:\Users\sebas\AppData\Local\Temp\ipykernel_3968\969169418.py:2: DtypeWarning: Columns (11: Sun2, 12: Sun3, 13: Sun4, 14: Sun5, 15: Notes) have mixed types. Specify dtype option on import or set low_memory=False.
  target = pd.read_csv(TARGET_PATH)

In [5]:
train_subset = train[TARGET_COLUMNS]
target_subset = target[TARGET_COLUMNS]

print("TRAINING PREVIEW")
display(train_subset.head())

print("TARGET PREVIEW")
display(target_subset.head())

TRAINING PREVIEW

,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup
0,All others,UnItemised brand,NaN,External Analgesics,Creams/Gels & Medicated Patches,Adult
1,All others,UnItemised brand,NaN,Internal Analgesics,Speciality Pain,Adult
2,NaN,UnItemised brand,NaN,"Vitamins, Minerals & Supplements",NaN,NaN
3,All others,Centrum,NaN,"Vitamins, Minerals & Supplements",Multivitamins,Adult
4,All others,UnItemised brand,NaN,Internal Analgesics,Speciality Pain,Adult

TARGET PREVIEW

   Mnfr  Brand  Platform  Segment  Sub-Segment  TargetAgeGroup
0   NaN    NaN       NaN      NaN          NaN             NaN
1   NaN    NaN       NaN      NaN          NaN             NaN
2   NaN    NaN       NaN      NaN          NaN             NaN
3   NaN    NaN       NaN      NaN          NaN             NaN
4   NaN    NaN       NaN      NaN          NaN             NaN

In [6]:
print("TRAINING DATA TYPES")
display(train_subset[TARGET_COLUMNS].dtypes.rename("dtype").to_frame())

print("TARGET DATA TYPES")
display(target_subset[TARGET_COLUMNS].dtypes.rename("dtype").to_frame())

TRAINING DATA TYPES

               dtype
Mnfr             str
Brand            str
Platform         str
Segment          str
Sub-Segment      str
TargetAgeGroup   str

TARGET DATA TYPES

                  dtype
Mnfr            float64
Brand           float64
Platform        float64
Segment         float64
Sub-Segment     float64
TargetAgeGroup  float64

In [7]:
print("\nUnique Platform labels:")
print(train["Platform"].value_counts(dropna=False))

Unique Platform labels:
Platform
NaN                                                                                                     83447
Extra Strength                                                                                             84
Children                                                                                                   72
Pain + Fever                                                                                               51
Oral Suspension                                                                                            49
                                                                                                        ...
12 Hour Relief                                                                                              1
 orange juice or a smoothie daily; unflavored GRASS-FED: Super Collagen Peptides powder is grass-fed        1
Cold Max                                                                                                    1
SmartCheck                                                                                                  1
Effective in 15 Minutes                                                                                     1
Name: count, Length: 64, dtype: int64

In [8]:
print("Number of Unique Platform labels:",train["Platform"].nunique())
print("Number of Unique Stripped Platform labels:",train["Platform"].astype("string").str.strip().nunique())
length_series=train["Platform"].astype("string").str.split().str.len().value_counts().sort_index()
display(length_series)

Number of Unique Platform labels: 63
Number of Unique Stripped Platform labels: 63

Platform
1     384
2     485
3     178
4      47
6      10
14      1
Name: count, dtype: int64

In [9]:
platform_col=train["Platform"].astype("string")
str_list = set()
for length in length_series.index:
    print(f"\n--- Length {length} ---")
    length_list = platform_col[platform_col.str.split().str.len() == length].unique().tolist()
    print(length_list)
    str_list.update(length_list)

--- Length 1 ---
['Cream', 'Children', 'Multi-Symptom', 'Sleep', 'Allergy', 'Complete', 'Sinus', 'Ultratabs', 'Throat', 'Immune', 'Chewables', 'Arthritis', 'Nasal', 'Precise', 'Tension', 'Head', 'PM', 'Patch', 'Gel', 'SmartCheck', 'Syrup']

--- Length 2 ---
['Red Eye', 'Regular Strength', 'Liquid Gels', 'Sinus Plus', 'Maximum Strength', 'Motrin IB', 'Dissolve Packs', 'Dual Action', 'Oral Suspension', 'Migraine Caplets', 'Extra Strength', 'Oral Solution', 'Dry Eye', 'Concentrated Drops', 'Sinus Severe', 'Imodium A-D', 'Original Strength', 'Tylenol PM', 'Simply Sleep', 'Pain Relief', 'Motrin PM', 'Coated Tabs', 'Cold Max', 'Dissolve Tablets', ' grass fed', 'Head Care']

--- Length 3 ---
['Allergy Plus Congestion', '24 Hour Relief', 'Pain + Fever', 'Cold + Flu', 'Arthritis Pain Relief', 'Vits & Supps', 'Rapid Release Gels', 'Head + Cold', 'Sinus + Headache', '12 Hour Relief']

--- Length 4 ---
['Eight Hour Arthritis Pain', 'Eight Hour Muscle Aches', 'Effective in 15 Minutes']

--- Length 6 ---
['Cough + Cold + Sore Throat', 'Cold + Cough + Runny Nose']

--- Length 14 ---
[' orange juice or a smoothie daily; unflavored GRASS-FED: Super Collagen Peptides powder is grass-fed']

In [10]:
train[train["Platform"]==" grass fed"]

,Exclude,JoiningKey,Retailer,Category,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup,Sun1,Sun2,Sun3,Sun4,Sun5,Notes,ProductCategory,ProductBrand,ProductName,ProductRating,ProductReviewsCount,XRatXRev,ReviewsCount,Sku,Upc,ProductModelNumber,ProductUrl,ProductImageUrl,MDM_InsertDateTime,MDM_Id,ProductDescription,ProductContents
43276,HYDROLYZED COLLAGEN: Provides some of the amino acids our bodies need to ma...,which is found in our nails and hair* AMINO ACIDS AND VITAMIN C: Nourish yo...,19 amino acids nourish the skins dermal layers; and Vitamin C,an essential antioxidant,aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C ...,gluten-free,grass fed,IGEN Non-GMO tested.* No soy wheat,lactose,"starch or artificial flavors; 3 tablets daily""","Protein, Vitamin C (as calcium ascorbate), Biotin, Sodium, Hydrolyzed bovine...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70020,HYDROLYZED COLLAGEN: Provides some of the amino acids our bodies need to ma...,which is found in our nails and hair* AMINO ACIDS AND VITAMIN C: Nourish yo...,19 amino acids nourish the skins dermal layers; and Vitamin C,an essential antioxidant,aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C ...,gluten-free,grass fed,IGEN Non-GMO tested.* No soy wheat,lactose,starch or artificial flavors; 3 tablets daily NeoCell Super Collagen + Vita...,and formulated for healthy hair,beautiful skin,and nail support.* As we age,our collagen gets depleted,which can lead to many common signs of aging. NeoCell Super Collagen + Vita...,treat,cure,or prevent any disease; This product does not contain common GE genes or pr...,Serving Size 3 Tablets. Calories: 10; Protein: 3 g; Vitamin C (as calcium as...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
text_cols = train.select_dtypes(include=["object", "string"]).columns

str_lengths = train[text_cols].apply(lambda col: col.astype("string").str.len())

print(str_lengths.mean(axis=1).describe(percentiles=[0.6,0.95,0.99]))

count       84552.0
mean      70.850717
std        48.97338
min       11.416667
60%       59.333333
95%      169.732609
99%      234.476818
max          765.85
dtype: Float64

In [ ]:
def run_whitelist_filter(df:pd.DataFrame)-> pd.DataFrame:
    quarantined_dict=dict()
    quarantined_df = None

    for col in TARGET_COLUMNS:
        quarantined_df.concat(df[df[col]!=f"{col}_whitelist"])
        quarantined_dict[col]=len(quarantined_df)

    quarantined_df=quarantined_df.drop_duplicates
    return df.drop(index=quarantined_df.index), quarantined_df

In [31]:
# average missingness per row
def get_avg_missingingness(df:pd.DataFrame):
    return df.isna().mean(axis=1).median()

In [ ]:
# calculate average text length per row
def get_avg_row_str_len(df:pd.DataFrame): 
    text_cols = df.select_dtypes(include=["object", "string"]).columns
    str_lengths = df[text_cols].apply(lambda col: col.astype("string").str.len())
    return str_lengths.mean(axis=1).median()

In [ ]:
def get_avg_label_occurance_dict(df:pd.DataFrame):
    avg_occurance = dict()

    for col in TARGET_COLUMNS:

        current_col=df[col].astype("string")
        label_occurance = current_col.value_counts().sort_index()
        avg_occurance[col] = label_occurance.median()

    return avg_occurance

In [ ]:
def check_target_cols(df:pd.DataFrame):
    quarantined_rows = []

    average_missingness = get_avg_missingingness(df)
    average_row_len = get_avg_row_str_len(df)

    # checking criteria for each target column
    for col in TARGET_COLUMNS:
        print(f"\n---{col}---")
        # counts the rows that hold certain label lengths 
        length_series=df[col].astype("string").str.split().str.len().value_counts().sort_index()

        # get a list of all labels
        current_col=df[col].astype("string")
        label_list = set(current_col.dropna().unique())

        # check each label's first index for whitespace or lower case letters
        for label in label_list:
            # `if label...` for empty strings ""
            if label and (label.startswith(" ") or label[0].islower()):

                # calculate that label's rows average missingness and text length
                missingness = df[df[col] == label].isna().mean(axis=1).mean()
                row_len = str_lengths[df[col] == label].mean(axis=1).median()
                if missingness > average_missingness or row_len > average_row_len:
                    print(
                        f"Label: {label}, \n"
                        f"Avg. missing percent: {missingness:.2%}, \n"
                        f"Avg. string length: {row_len:.2f}, \n"
                        f"Number of rows: {(current_col == label).sum()}\n"
                    )
                    faulty_label = df[df[col] == label]
                    quarantined_rows.append(faulty_label)

        """
        try to turn all columns numeric.
        faulty rows tend to replace numeric columns with str, so
        they will have NA across the entire row.
        """
        numeric = df.apply(pd.to_numeric, errors="coerce")
        non_numeric_mask = numeric.isna().all(axis=1)
        quarantined_rows.append(df[non_numeric_mask])

    if quarantined_rows:
        quarantined_df_1 = pd.concat(quarantined_rows, ignore_index=False).drop_duplicates()

    df, quarantined_df_2 = run_whitelist_filter(df)

    # remove quarantined rows
    df.drop(index=quarantined_df.index)

    # calculate average label occurance per target column
    avg_occurance = get_avg_label_occurance_dict(df)
    average_missingness = get_avg_missingingness(df)
    average_row_len = get_avg_row_str_len(df)

    for col in TARGET_COLUMNS:
        if len(df[df[col] in label_list])




        
    print(avg_occurance)
    return quarantined_df

quarantined_df=check_target_cols(train)

---Mnfr---
Label:  aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C & Biotin is Keto certified,
Avg. missing percent: 53.12%,
Avg. string length: 81.96,
Number of rows: 2

Label:  coffee,
Avg. missing percent: 53.12%,
Avg. string length: 57.20,
Number of rows: 1


---Brand---
Label:  tea,
Avg. missing percent: 53.12%,
Avg. string length: 57.20,
Number of rows: 1

Label:  gluten-free,
Avg. missing percent: 53.12%,
Avg. string length: 81.96,
Number of rows: 2


---Platform---
Label:  orange juice or a smoothie daily; unflavored GRASS-FED: Super Collagen Peptides powder is grass-fed,
Avg. missing percent: 53.12%,
Avg. string length: 57.20,
Number of rows: 1

Label:  grass fed,
Avg. missing percent: 53.12%,
Avg. string length: 81.96,
Number of rows: 2


---Segment---
Label:  IGEN Non-GMO tested.* No soy wheat,
Avg. missing percent: 53.12%,
Avg. string length: 81.96,
Number of rows: 2

Label:  Keto certified,
Avg. missing percent: 53.12%,
Avg. string length: 57.20,
Number of rows: 1


---Sub-Segment---
Label:  lactose,
Avg. missing percent: 53.12%,
Avg. string length: 81.96,
Number of rows: 2

Label:  gluten-free,
Avg. missing percent: 53.12%,
Avg. string length: 57.20,
Number of rows: 1


---TargetAgeGroup---
Label:  starch or artificial flavors; 3 tablets daily",
Avg. missing percent: 65.62%,
Avg. string length: 65.82,
Number of rows: 1

Label:  Paleo friendly,
Avg. missing percent: 53.12%,
Avg. string length: 57.20,
Number of rows: 1

Label:  starch or artificial flavors; 3 tablets daily NeoCell Super Collagen + Vitamin C and Biotin is made with grass-fed hydrolyzed collagen,
Avg. missing percent: 40.62%,
Avg. string length: 98.11,
Number of rows: 1

{'Mnfr': np.float64(516.0), 'Brand': np.float64(140.5), 'Platform': np.float64(10.0), 'Segment': np.float64(4409.0), 'Sub-Segment': np.float64(430.0), 'TargetAgeGroup': np.float64(380.0)}

In [22]:
len(quarantined_df)

4

In [23]:
quarantined_df

,Exclude,JoiningKey,Retailer,Category,Mnfr,Brand,Platform,Segment,Sub-Segment,TargetAgeGroup,Sun1,Sun2,Sun3,Sun4,Sun5,Notes,ProductCategory,ProductBrand,ProductName,ProductRating,ProductReviewsCount,XRatXRev,ReviewsCount,Sku,Upc,ProductModelNumber,ProductUrl,ProductImageUrl,MDM_InsertDateTime,MDM_Id,ProductDescription,ProductContents
43276,HYDROLYZED COLLAGEN: Provides some of the amino acids our bodies need to ma...,which is found in our nails and hair* AMINO ACIDS AND VITAMIN C: Nourish yo...,19 amino acids nourish the skins dermal layers; and Vitamin C,an essential antioxidant,aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C ...,gluten-free,grass fed,IGEN Non-GMO tested.* No soy wheat,lactose,"starch or artificial flavors; 3 tablets daily""","Protein, Vitamin C (as calcium ascorbate), Biotin, Sodium, Hydrolyzed bovine...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70020,HYDROLYZED COLLAGEN: Provides some of the amino acids our bodies need to ma...,which is found in our nails and hair* AMINO ACIDS AND VITAMIN C: Nourish yo...,19 amino acids nourish the skins dermal layers; and Vitamin C,an essential antioxidant,aids in collagen formation* GRASS-FED COLLAGEN: Super Collagen + Vitamin C ...,gluten-free,grass fed,IGEN Non-GMO tested.* No soy wheat,lactose,starch or artificial flavors; 3 tablets daily NeoCell Super Collagen + Vita...,and formulated for healthy hair,beautiful skin,and nail support.* As we age,our collagen gets depleted,which can lead to many common signs of aging. NeoCell Super Collagen + Vita...,treat,cure,or prevent any disease; This product does not contain common GE genes or pr...,Serving Size 3 Tablets. Calories: 10; Protein: 3 g; Vitamin C (as calcium as...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21527,SUPPORTS COLLAGEN FORMATION FOR MEN AND WOMEN: Collagen supplement for men ...,promotes healthy collagen formation throughout the body,and supports healthy joints* SUGGESTED USE FOR MONTHLY SUPPLY: 30-day,1-month supply; simply dissolve 2 scoops of Super Collagen Peptides powder ...,coffee,tea,orange juice or a smoothie daily; unflavored GRASS-FED: Super Collagen Pept...,Keto certified,gluten-free,Paleo friendly,IGEN Non-GMO tested;* contains no soy wheat,lactose,starch,"corn or artificial flavors""",Serving Size 2 Scoops (20 g). Servings per Container 30. Calories: 70; Prote...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48935,Inactive Ingredients: Croscarmellose sodium,Lactose,"Magnesium stearate.""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN